import { WebsiteModel } from './types';

export const WHATSAPP_NUMBER = '5585996722994';
export const WHATSAPP_BASE_URL = `https://wa.me/${WHATSAPP_NUMBER}`;

export const WEBSITE_MODELS: WebsiteModel[] = [
  {
    id: '2',
    title: 'Lumina Solar',
    description: 'Landing page de alta conversão para empresas de energia solar e soluções sustentáveis.',
    category: 'Energia Solar',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://lumina-solar-01.netlify.app',
    demoUrl: 'https://lumina-solar-01.netlify.app',
  },
  {
    id: '3',
    title: 'Prime Eventos',
    description: 'Plataforma elegante para cerimonialistas, festas corporativas e eventos sociais.',
    category: 'Eventos',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://prime-eventos.netlify.app',
    demoUrl: 'https://prime-eventos.netlify.app',
  },
  {
    id: '4',
    title: 'Calango Lab',
    description: 'Site moderno para startups, laboratórios de inovação e desenvolvimento de software.',
    category: 'Tecnologia',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://calangolab.netlify.app',
    demoUrl: 'https://calangolab.netlify.app',
  },
  {
    id: '5',
    title: 'Instituto Horizon',
    description: 'Apresentação institucional de excelência para fundações, ONGs e projetos educacionais.',
    category: 'Institucional',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://instituto-horizon.netlify.app',
    demoUrl: 'https://instituto-horizon.netlify.app',
  },
  {
    id: '6',
    title: 'Credivalle',
    description: 'Landing page para correspondentes bancários, crédito e consultoria financeira.',
    category: 'Financeiro',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://credivalle.netlify.app',
    demoUrl: 'https://credivalle.netlify.app',
  },
  {
    id: '7',
    title: 'Pousada Recanto',
    description: 'Design acolhedor para pousadas e hotéis com destaque para acomodações e reservas.',
    category: 'Hotelaria',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://pousada-recanto.netlify.app',
    demoUrl: 'https://pousada-recanto.netlify.app',
  },
  {
    id: '8',
    title: 'Vanguard Advocacia',
    description: 'Presença digital sóbria e imponente para escritórios de advocacia e consultoria jurídica.',
    category: 'Advocacia',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://vanguard-advocacia.netlify.app',
    demoUrl: 'https://vanguard-advocacia.netlify.app',
  },
  {
    id: '9',
    title: 'Contábil Inteligente',
    description: 'Soluções completas para escritórios contábeis, gestão fiscal e BPO financeiro.',
    category: 'Contabilidade',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://coruscating-gecko-f4f516.netlify.app',
    demoUrl: 'https://coruscating-gecko-f4f516.netlify.app',
  },
  {
    id: '10',
    title: 'Sabor & Cia',
    description: 'Cardápio digital dinâmico e integrado para restaurantes, lanchonetes e delivery.',
    category: 'Delivery',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://sabor-cia01.netlify.app',
    demoUrl: 'https://sabor-cia01.netlify.app',
  },
  {
    id: '11',
    title: 'Odonto Smile',
    description: 'Design focado em agendamento de consultas e apresentação de tratamentos odontológicos.',
    category: 'Odontologia',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://odontosmile01.netlify.app',
    demoUrl: 'https://odontosmile01.netlify.app',
  },
  {
    id: '12',
    title: 'Bella Pizza',
    description: 'Landing page apetitosa para pizzarias e gastronomia com pedidos direto no WhatsApp.',
    category: 'Pizzaria',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://bellapizza01.netlify.app',
    demoUrl: 'https://bellapizza01.netlify.app',
  },
  {
    id: '13',
    title: 'Vitta Estética',
    description: 'Visual clean e sofisticado para clínicas de estética, spas e cuidados corporais.',
    category: 'Saúde e Beleza',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://vittaestetica01.netlify.app',
    demoUrl: 'https://vittaestetica01.netlify.app',
  },
  {
    id: '14',
    title: 'RV Comunicação Visual',
    description: 'Portfólio de alto impacto para gráficas, comunicação visual e fachadas comerciais.',
    category: 'Serviços',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://rvcomunicacaovisual.netlify.app',
    demoUrl: 'https://rvcomunicacaovisual.netlify.app',
  },
  {
    id: '15',
    title: 'NE Advocacia',
    description: 'Advocacia de alto padrão em Baturité e Ceará. Dra. Janaína Nunes (OAB/CE 11.606) e Dra. Yara Evangelista Rodrigues (OAB/CE 19.326) | Direito Civil e Trabalhista.',
    category: 'Advocacia',
    imageUrl: 'https://image.thum.io/get/width/600/crop/800/https://neadvocacia.netlify.app',
    demoUrl: 'https://neadvocacia.netlify.app',
  },
];

